### ISSUE TITLE
Demo app is not working for me

### ISSUE THREAD

**Issue by grzegorz-silarski** [jpmens/tempgauge#4]
![error](https://cloud.githubusercontent.com/assets/3469443/2799862/1f653482-cc68-11e3-8f9a-4a91e0b1b2e1.png)

**Comment by jpmens** [comment]
Without more information on how you did what there's nothing I can do.

**Comment by grzegorz-silarski** [comment]
I was just going to http://test.mosquitto.org/gauge/ website, and then i got this error on load. I'm using google chrome. Should I do somethig else with the Demo for it to work?

**Comment by jpmens** [comment]
Ah, that site is not under our control. I will inform the site operator.
