### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by clecomte** [jpmens/tempgauge#5]
Hi,

I try the demo http://test.mosquitto.org/gauge/ , but it gives me this error in the webbrowser : **Connection failed: AMQJSC0001E Connect timed out**.

With a local installation :
And with a mosquitto on localhost, I have this error : **Connection failed: AMQJS0007E Socket error:undefined**.

And WSS :
./WSS_static_armv6 --websocketPort 18883 --brokerHost localhost --brokerPort 1883
2018-02-22T13:12:45 [16] Unexpected EOF from remote endpoint, terminating connection.
2018-02-22T13:13:59 [16] Unexpected EOF from remote endpoint, terminating connection.

Do you have an idea of the problem ?
kind regards

**Comment by jpmens** [comment]
The Mosquitto test server is not  under our control; you'll have to contact the project.

Your local installation is either improperly configured or has no Websocket support. Please refer to Mosquitto documentation on how to do that.

I'm not even sure if WSS is still being maintained; here too, I have to send you to that project.

**Comment by clecomte** [comment]
The mosquitto server works well, I'am using it for another project
I think the client doesn't establish correctly the connexion.

And I have the same problem with the connexion to WSS.

Le 22/02/2018 à 16:16, JP Mens a écrit :

**Comment by doquen** [comment]
Hi, i'm having the same problem. Message Connection failed: AMQJSC0001E Connect timed out appears in browser.

**Comment by jpmens** [comment]
Show me your Mosquitto configuration please; the websockets portion

**Comment by crobles** [comment]
hello.

My Mosquitto server use TLS...
how can i use your example with TLS connection?.
can you give me an example?

thanx
